"""Property-based tests for Starlark evaluation."""

from __future__ import annotations

import math
from typing import Any

import hypothesis.strategies as st
import pytest
from hypothesis import given, settings

import starlark
from starlark.eval.values import repr_starlark

# Only Starlark's own exception types are expected to escape the public
# `eval`/`exec_file` entry points.
# Any other Python exception (`ValueError`, `OverflowError`, `RecursionError`, ...)
# indicates a bug in the interpreter.
ALLOWED_EXCEPTIONS = (
    starlark.EvalError,
    starlark.StarlarkSyntaxException,
)


@given(st.text(max_size=1000))
@settings(deadline=None, max_examples=500)
def test_eval_handles_arbitrary_strings_without_crashing(source: str):
    """Verify that evaluation of arbitrary strings
    only raises expected Starlark exceptions or standard resource/parsing limits,
    never unhandled Python interpreter crashes."""
    try:
        starlark.eval(source, max_steps=100, max_allocs=10000)
    except ALLOWED_EXCEPTIONS:
        pass


@given(st.text(max_size=1000))
@settings(deadline=None, max_examples=500)
def test_exec_handles_arbitrary_strings_without_crashing(source: str):
    """Verify that execution of arbitrary strings
    only raises expected Starlark exceptions or standard resource/parsing limits,
    never unhandled Python interpreter crashes."""
    try:
        starlark.exec_file(source, max_steps=100, max_allocs=10000)
    except ALLOWED_EXCEPTIONS:
        pass


# Strategy for Starlark-compatible Python values.
# Limit sizes and depths to keep test execution fast while still exercising nested structures.
# Float keys are intentionally excluded from dicts: NaN would break equality,
# and Starlark dicts rarely use float keys in practice.
# NaN and infinity are excluded from the value strategy altogether
# because Starlark has no literals for them;
# the repr-based round-trip test cannot evaluate those values.
starlark_values = st.recursive(
    st.none()
    | st.booleans()
    | st.integers(min_value=-(10**15), max_value=10**15)
    | st.floats(allow_nan=False, allow_infinity=False)
    | st.text(max_size=100),
    lambda children: (
        st.lists(children, max_size=5)
        | st.dictionaries(
            st.text(max_size=50) | st.integers(min_value=-1000, max_value=1000) | st.booleans(),
            children,
            max_size=5,
        )
        | st.tuples(children)
    ),
    max_leaves=10,
)


def assert_equivalent(a: Any, b: Any) -> None:
    """Recursively assert equivalence of Python values, treating tuples and lists as equivalent."""
    if type(a) is not type(b):
        # Starlark's from_value converts tuples to lists, so treat them as equivalent.
        if isinstance(a, (list, tuple)) and isinstance(b, (list, tuple)):
            pass
        else:
            raise AssertionError(f"Type mismatch: {type(a)} vs {type(b)}")

    if isinstance(a, (list, tuple)):
        assert len(a) == len(b), f"Length mismatch: {len(a)} vs {len(b)}"
        for x, y in zip(a, b, strict=False):
            assert_equivalent(x, y)
    elif isinstance(a, dict):
        assert len(a) == len(b), f"Dict length mismatch: {len(a)} vs {len(b)}"
        for k in a:
            assert k in b, f"Key {k} missing from second dict"
            assert_equivalent(a[k], b[k])
    elif isinstance(a, float):
        # NaN and infinity are not generated by the strategy, so we only
        # need to check finite float equality (including negative zero).
        assert a == b

        if a == 0.0:
            assert isinstance(b, float)
            assert math.copysign(1.0, a) == math.copysign(1.0, b)
    else:
        assert a == b


@given(starlark_values)
@settings(deadline=None)
def test_value_roundtrips_to_starlark_and_back(val):
    """Verify that converting Python values to Starlark and back,
    or evaluating their repr, preserves equivalence."""
    # Convert Python value to Starlark value and back.
    sv = starlark.to_value(val)
    py_val = starlark.from_value(sv)
    assert_equivalent(py_val, val)

    # Convert Starlark value to its string representation, evaluate it, and convert back.
    r = repr_starlark(sv)
    evaluated = starlark.eval(r)
    py_evaluated = starlark.from_value(evaluated)
    assert_equivalent(py_evaluated, val)


def test_mutability_token_enforces_freeze():
    """Verify that mutating a list or dict
    after freezing its mutability token raises EvalError."""
    mut = starlark.Mutability("test")

    lst = starlark.to_value([1, 2, 3], mutability=mut)
    d = starlark.to_value({"a": 1}, mutability=mut)

    lst.append(4)
    d["b"] = 2
    assert list(lst) == [1, 2, 3, 4]
    assert d["b"] == 2

    mut.freeze()

    with pytest.raises(starlark.EvalError):
        lst.append(5)
    with pytest.raises(starlark.EvalError):
        d["c"] = 3


def test_to_value_rejects_unsupported_types():
    """Verify that to_value raises UnsupportedTypeError for custom Python classes."""

    class CustomObject:
        pass

    with pytest.raises(starlark.UnsupportedTypeError):
        starlark.to_value(CustomObject())
