name: release-helper
on:
  issue_comment:
    types: [created, edited]
permissions:
  contents: read

jobs:
  release-helper:
    if: startsWith(github.event.comment.body, '@bazel-io ')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: audit

      - name: Run helper
        uses: bazelbuild/continuous-integration/actions/release-helper@8e39c913e35bc4e9a76f5665b59614ace18e0f11 # master
        with:
          token: ${{ secrets.BAZEL_IO_TOKEN }}
